/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.awt.HeadlessException;
import static java.lang.Thread.sleep;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author matte
 */
public class chatFrame extends javax.swing.JFrame {

    /**
     * Creates new form testFrame
     */
    Condivisa c;
    gestioneEventi g;

    public chatFrame(Condivisa c, gestioneEventi g) throws HeadlessException {
        initComponents();
        this.c = c;
        this.g = g;
        c.frame = this;
    }

    public chatFrame() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtChat = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        btnConnetti = new javax.swing.JButton();
        txtMessaggio = new javax.swing.JTextField();
        btnInvia2 = new javax.swing.JButton();
        chiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtChat.setText("chat");

        txtDestinatario.setText("destinatario");

        btnConnetti.setText("connetti");
        btnConnetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnettiActionPerformed(evt);
            }
        });

        txtMessaggio.setText("messaggio");

        btnInvia2.setText("invia");
        btnInvia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvia2ActionPerformed(evt);
            }
        });

        chiudi.setText("disconnetti");
        chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConnetti)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInvia2)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chiudi)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnetti))
                .addGap(18, 18, 18)
                .addComponent(txtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvia2))
                .addGap(18, 18, 18)
                .addComponent(chiudi)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnettiActionPerformed
        try {
            // TODO add your handling code here:
            g.connetti();
        } catch (UnknownHostException ex) {
            Logger.getLogger(chatFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConnettiActionPerformed

    private void btnInvia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvia2ActionPerformed
        // TODO add your handling code here:
        g.invia(txtMessaggio.getText());
    }//GEN-LAST:event_btnInvia2ActionPerformed

    private void chiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiudiActionPerformed
        // TODO add your handling code here:
        g.disconnetti();
    }//GEN-LAST:event_chiudiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException, SocketException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        Condivisa c = new Condivisa();
        gestioneEventi g = new gestioneEventi(c);
        ThreadRicevi tr = new ThreadRicevi(c);
        ThreadInvio ti = new ThreadInvio(c);
        ThreadElabora te = new ThreadElabora(c, g);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chatFrame(c, g).setVisible(true);
            }
        });

        tr.start();
        ti.start();
        te.start();
    }

    public String GetAddress() {
        return txtDestinatario.getText();
    }

    public String GetLabel() {
        return txtChat.getText();
    }

    /**
     * @brief setta la label JLabel1 in un contesto thread safe richiama la
     * funzione SwingUtilities che permette di eseguire un update alla grafica (
     * swing ) in un contesto invocato ( e quindi gestito del thread grafico )
     * @param s String stringa da impostare alla labet
     */
    public void Setlabel(String s) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                //Codice da eseguire nel Thread grafico
                txtChat.setText(s);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnetti;
    private javax.swing.JButton btnInvia2;
    private javax.swing.JButton chiudi;
    private javax.swing.JLabel txtChat;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtMessaggio;
    // End of variables declaration//GEN-END:variables
}
